In [1]:
import tensorflow as tf

#### 创建
 tf.random.normal(shape, mean=0.0, stddev=1.0)可以创建形状为 shape，均值为
mean，标准差为 stddev 的正态分布𝒩

In [3]:
a = tf.random.normal([4,28,28,3]) #创建正态分布的张量
a

<tf.Tensor: shape=(4, 28, 28, 3), dtype=float32, numpy=
array([[[[-0.04219975,  0.33539358, -1.1632028 ],
         [ 0.7293999 ,  0.06585251,  0.339679  ],
         [-0.3322032 ,  0.21430264, -0.32370117],
         ...,
         [ 0.49014625, -0.60501105, -1.2466427 ],
         [ 0.45629337,  1.3692884 , -1.3381057 ],
         [ 0.27377704, -1.8736844 , -0.07905036]],

        [[ 0.6490601 ,  0.5370017 , -0.42824918],
         [ 0.75542474, -1.7794393 ,  1.0931976 ],
         [ 0.34752986, -1.2337846 , -0.01674916],
         ...,
         [ 1.6024972 , -0.02615147, -0.8408024 ],
         [ 0.25811476, -0.60522807,  1.4026978 ],
         [ 0.41508338, -0.49566135, -0.11193284]],

        [[-1.5916228 ,  0.51032764,  0.49893796],
         [-1.0210696 ,  0.44218427, -0.23572677],
         [-1.3259313 , -1.8384073 , -0.08096848],
         ...,
         [-1.1591917 , -1.8101687 ,  0.8541323 ],
         [ 1.35672   , -1.8049203 , -0.20676145],
         [ 1.7703195 ,  2.2849753 , -0.3763485 ]

In [7]:
a.shape,a.ndim

(TensorShape([4, 28, 28, 3]), 4)

In [8]:
tf.reshape(a,[4,28*28,3]).shape

TensorShape([4, 784, 3])

In [10]:
tf.reshape(a,[4,-1,3]).shape

TensorShape([4, 784, 3])

In [11]:
tf.reshape(a,[4,784*3]).shape

TensorShape([4, 2352])

In [12]:
tf.reshape(a,[4,-1]).shape

TensorShape([4, 2352])

In [13]:
a.shape,a.ndim

(TensorShape([4, 28, 28, 3]), 4)

### 矩阵的转置
[w,h]   [h,w]

In [15]:
a = tf.random.normal((4,3,2,1))

In [17]:
a.shape

TensorShape([4, 3, 2, 1])

In [19]:
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [20]:
tf.transpose(a,perm=[0,1,3,2]).shape

TensorShape([4, 3, 1, 2])

## 各种维度

- [b,h,w,c]  tensor
- [b,c,h,w]  使用[0,3,1,2]来进行交换  ptouch所接受

In [21]:
#增加一个维度 dim
a = tf.random.normal([4,35,8])

In [25]:
a = tf.expand_dims(a,axis=0).shape
a

TensorShape([1, 4])

In [23]:
#根据index 不同会在不同地方增加一个维度

In [29]:
#减少一个维度，只能较少维度为1的shape
tf.squeeze(a)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

#### Broadcasting 
在某一个维度上  复制n多次（扩张但不复制数据）  

相比于 tf.tile并不真正扩张 

In [30]:
#交换维度
x = tf.random.normal([2,32,32,3])
tf.transpose(x,perm=[0,3,1,2])    #即矩阵的转置

<tf.Tensor: shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[ 5.53583562e-01, -5.66579998e-01,  4.76825923e-01, ...,
          -2.29572034e+00, -1.19452357e+00, -6.31061852e-01],
         [-3.08524191e-01, -1.27622688e+00,  7.19740629e-01, ...,
          -1.45058370e+00, -7.61649787e-01, -1.02978490e-01],
         [-5.32325089e-01,  1.15621364e+00, -1.09892035e+00, ...,
          -1.40035713e+00, -1.93017140e-01,  1.06335747e+00],
         ...,
         [-1.12785371e-02, -1.92198026e+00, -1.24242139e+00, ...,
           1.80083954e+00,  1.60554433e+00, -1.68257546e+00],
         [-8.03810582e-02, -1.21191479e-01,  1.14049181e-01, ...,
          -7.17669189e-01,  5.30337572e-01, -6.67299986e-01],
         [ 8.38104665e-01,  1.39395928e+00,  9.77160335e-01, ...,
          -1.03569329e+00, -2.17502981e-01, -3.44386771e-02]],

        [[ 5.40398598e-01,  8.67668316e-02, -3.52484703e-01, ...,
          -4.42589968e-01,  8.75281215e-01, -2.02505517e+00],
         [ 4.98726010e-01,  4.37